name: "Destroy AWS EC2 with Ansible"
 
on: 
  workflow_dispatch:
  
env:
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
jobs:
 ansible:
   runs-on: ubuntu-latest
   steps:
     - name: "Setup Python Version"
       uses: actions/setup-python@v2
       with:
         python-version: 3.8

     - name: "Install Python dependencies"
       run: python -m pip install --upgrade pip

     - name: "Install Ansible"
       run: pip install ansible
      
    
