name: "Destroy Test Environment on AWS"

on:
  workflow_dispatch:

env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy:
    name: "Destroy AWS"
    runs-on: ubuntu-latest

    steps:
      - name: Destroy Test VM
        id: destroy
        run: terraform destroy -target aws_instance.weather_test_instance